name: task_manager
description: "TaskManager app for devices"

publish_to: 'none'

version: 1.1.4

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.15.7
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  file_picker: ^6.2.0
  firebase_auth: ^4.17.7
  firebase_core: ^2.26.0
  firebase_core_platform_interface: 5.0.0
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.0.2
  flutter_modular: ^6.3.2
  google_sign_in: 6.2.1
  json_annotation: ^4.8.1
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - firebase_constants.env

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 600
  
